### ISSUE TITLE
Server not receiving models_committed events

### ISSUE THREAD

**Issue by lukeyeager** [lukeyeager/flask-sqlalchemy-socketio-demo#1]
While the server is running, I run `./main.py add_update` in a separate terminal to add a new DB entry. In the separate terminal, I'm getting the event:

```
$ ./main.py add_update
PUBLISH - insert <Update "Added from command-line" at 2016-01-09 18:34:29.744304>
Added <Update "Added from command-line" at 2016-01-09 18:34:29.744304>
```

But I don't see a similar `PUBLISH` message in the server output.

When I refresh the page, the new update exists. So this isn't a DB connectivity issue.

**Comment by lukeyeager** [comment]
I'm worried that I may not be able to subscribe to events that happen in another session.

**Comment by ThiefMaster** [comment]
What you are trying to do is impossible. `models_committed` only works in the same process where the commit comes from (it's not a DB-level notification, it's sqlalchemy after committing to the DB).

**Comment by lukeyeager** [comment]
Oh, then that's pretty clear. Thanks @ThiefMaster! That wasn't obvious to me from the documentation. I had assumed it was using database hooks.

**Comment by ThiefMaster** [comment]
You might want to use redis for this kind of notifications.  http://redis.io/topics/pubsub

**Comment by lukeyeager** [comment]
Isn't it true that some databases provide a subscription interface? As I understand it, I'd need to (1) write to the db and (2) publish a redis event everytime I make a change. I'd love it if I could simply write to the DB and have others subscribe to changes on the DB.

Maybe that's not possible either?

**Comment by ThiefMaster** [comment]
Postgres actually has one. But no idea how you would use this via SQLAlchemy.

http://www.postgresql.org/docs/current/static/sql-notify.html
http://initd.org/psycopg/docs/advanced.html#asynchronous-notifications

**Comment by lukeyeager** [comment]
This isn't looking encouraging either:
https://www.quora.com/Can-socket-io-subscribe-to-changes-in-a-mysql-database

**Comment by ThiefMaster** [comment]
For what do you want to use this btw? Maybe there's a better way..

**Comment by lukeyeager** [comment]
Multi-node [DIGITS](https://github.com/NVIDIA/DIGITS). Flask app/SocketIO server on one node which kicks off workers on other nodes. Those other nodes save their results to a database (they don't communicate back to the server directly).

It would be great to require redis **OR** a SQL database - not both. You can't use SQLAlchemy with a redis backend, right?

**Comment by ThiefMaster** [comment]
No, but for persistent/structured data SQL databases are great, while Redis is great for pub/sub and simply key-value pairs (caching is a good example). So it sounds a lot like something where mixing those two makes sense. Or maybe even consider something like Celery if you just want to run tasks on those other nodes?

**Comment by lukeyeager** [comment]
I've looked into Celery, but we're not going to have persistent worker nodes. We're working on an interface for creating new docker instances on the fly when we need them.

https://blog.andyet.com/2015/04/06/postgres-pubsub-with-json/

I might spend a little time looking into how hard it would be to integrate something like that into Flask-SQLAlchemy (or maybe directly into SQLAlchemy?). Do you think they would consider integrating a PR like that?

**Comment by ThiefMaster** [comment]
Try #sqlalchemy on freenode or the sqlalchemy mailing list on google groups. The developer of SQLalchemy is _very_ active and helpful

**Comment by lukeyeager** [comment]
Will do. Thanks again.
